[profile.default]
libs = ['lib']
out = 'out'
src = 'src'

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${RPC_URL}"

[etherscan]
goerli = {key = "${ETHERSCAN_API_KEY}"}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
